# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Heavily inspired from: https://github.com/DV8FromTheWorld/JDA-Website/blob/master/mkdocs.yml
theme:
  features:
    - navigation.instant # Faster loading
    - navigation.tabs # Top level horizontal tabs
    - toc.integrate # Integrated Table Of Contents (shows #, ##... sections)
    - content.code.annotate # Annotations on lines of codeicon:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

site_name: BotCommands Wiki

repo_name: BotCommands
repo_url: https://github.com/freya022/BotCommands
edit_uri: ../BotCommands-Wiki/edit/master/docs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/freya022/BotCommands
    - icon: fontawesome/brands/discord
      link: https://discord.gg/frpCcQfvTz

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Using commands:
      - Writing prefixed commands: using-commands/Prefixed-commands.md
      - Writing slash commands: using-commands/Slash-commands.md
      - Writing context menu commands: using-commands/Context-menu-commands.md
      - Updating application commands:
          - Slash commands - Updating option choices: using-commands/updating-application-commands/Slash-commands---Updating-option-choices.md
          - Updating privileges: using-commands/updating-application-commands/Updating-privileges.md
      - Inferred option names: using-commands/Inferred-option-names.md
  - Using components:
      - The Components API: using-components/The-Components-API.md
      - Buttons: using-components/Buttons.md
      - Selection menus: using-components/Selection-menus.md
  - Writing extensions:
      - Creating parameter resolvers: writing-extensions/Creating-parameter-resolvers.md #TODO move to each command type's wiki as to show the different interfaces
      - Constructor injection: writing-extensions/Constructor-injection.md
      - Field injection: writing-extensions/Field-injection.md
  - Misc:
      - Conditional instancing: misc/Conditional-instancing.md
      - Using instance suppliers: misc/Instance-suppliers.md
      - Using the event waiter: misc/The-event-waiter.md
  - Logging: Logging.md