name: Build docs site
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The BotCommands version this wiki deployment is for'
        required: true
      alias:
        description: 'The version alias for this deployment'
        required: true
        default: 'dev'
        type: choice
        options:
          - latest
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - run: |
          git fetch origin gh-pages --depth=1
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mike deploy ${{ inputs.version }} ${{ inputs.alias }} --update-aliases --push
